/**
 * generated by Xtext 2.9.0
 */
package sysml.dml;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sysml.dml.BS#getSingleS <em>Single S</em>}</li>
 *   <li>{@link sysml.dml.BS#getS <em>S</em>}</li>
 * </ul>
 *
 * @see sysml.dml.DmlPackage#getBS()
 * @model
 * @generated
 */
public interface BS extends EObject
{
  /**
   * Returns the value of the '<em><b>Single S</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Single S</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Single S</em>' containment reference.
   * @see #setSingleS(S)
   * @see sysml.dml.DmlPackage#getBS_SingleS()
   * @model containment="true"
   * @generated
   */
  S getSingleS();

  /**
   * Sets the value of the '{@link sysml.dml.BS#getSingleS <em>Single S</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Single S</em>' containment reference.
   * @see #getSingleS()
   * @generated
   */
  void setSingleS(S value);

  /**
   * Returns the value of the '<em><b>S</b></em>' containment reference list.
   * The list contents are of type {@link sysml.dml.S}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>S</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' containment reference list.
   * @see sysml.dml.DmlPackage#getBS_S()
   * @model containment="true"
   * @generated
   */
  EList<S> getS();

} // BS
