/**
 * generated by Xtext 2.9.0
 */
package sysml.dml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DI</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sysml.dml.DI#getId <em>Id</em>}</li>
 *   <li>{@link sysml.dml.DI#getB <em>B</em>}</li>
 *   <li>{@link sysml.dml.DI#getE <em>E</em>}</li>
 *   <li>{@link sysml.dml.DI#getClid <em>Clid</em>}</li>
 *   <li>{@link sysml.dml.DI#getCln <em>Cln</em>}</li>
 * </ul>
 *
 * @see sysml.dml.DmlPackage#getDI()
 * @model
 * @generated
 */
public interface DI extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' containment reference.
   * @see #setId(ID)
   * @see sysml.dml.DmlPackage#getDI_Id()
   * @model containment="true"
   * @generated
   */
  ID getId();

  /**
   * Sets the value of the '{@link sysml.dml.DI#getId <em>Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' containment reference.
   * @see #getId()
   * @generated
   */
  void setId(ID value);

  /**
   * Returns the value of the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>B</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' containment reference.
   * @see #setB(IS)
   * @see sysml.dml.DmlPackage#getDI_B()
   * @model containment="true"
   * @generated
   */
  IS getB();

  /**
   * Sets the value of the '{@link sysml.dml.DI#getB <em>B</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>B</em>' containment reference.
   * @see #getB()
   * @generated
   */
  void setB(IS value);

  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>E</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference.
   * @see #setE(IS)
   * @see sysml.dml.DmlPackage#getDI_E()
   * @model containment="true"
   * @generated
   */
  IS getE();

  /**
   * Sets the value of the '{@link sysml.dml.DI#getE <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' containment reference.
   * @see #getE()
   * @generated
   */
  void setE(IS value);

  /**
   * Returns the value of the '<em><b>Clid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Clid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clid</em>' attribute.
   * @see #setClid(String)
   * @see sysml.dml.DmlPackage#getDI_Clid()
   * @model
   * @generated
   */
  String getClid();

  /**
   * Sets the value of the '{@link sysml.dml.DI#getClid <em>Clid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Clid</em>' attribute.
   * @see #getClid()
   * @generated
   */
  void setClid(String value);

  /**
   * Returns the value of the '<em><b>Cln</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cln</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cln</em>' attribute.
   * @see #setCln(String)
   * @see sysml.dml.DmlPackage#getDI_Cln()
   * @model
   * @generated
   */
  String getCln();

  /**
   * Sets the value of the '{@link sysml.dml.DI#getCln <em>Cln</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cln</em>' attribute.
   * @see #getCln()
   * @generated
   */
  void setCln(String value);

} // DI
