/**
 * generated by Xtext 2.9.0
 */
package sysml.dml;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see sysml.dml.DmlFactory
 * @model kind="package"
 * @generated
 */
public interface DmlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dml";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.apache.org/sysml/Dml";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dml";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DmlPackage eINSTANCE = sysml.dml.impl.DmlPackageImpl.init();

  /**
   * The meta object id for the '{@link sysml.dml.impl.DImpl <em>D</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.DImpl
   * @see sysml.dml.impl.DmlPackageImpl#getD()
   * @generated
   */
  int D = 0;

  /**
   * The feature id for the '<em><b>F</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int D__F = 0;

  /**
   * The feature id for the '<em><b>S</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int D__S = 1;

  /**
   * The number of structural features of the '<em>D</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int D_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link sysml.dml.impl.FImpl <em>F</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.FImpl
   * @see sysml.dml.impl.DmlPackageImpl#getF()
   * @generated
   */
  int F = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int F__NAME = 0;

  /**
   * The feature id for the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int F__I = 1;

  /**
   * The feature id for the '<em><b>R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int F__R = 2;

  /**
   * The feature id for the '<em><b>S</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int F__S = 3;

  /**
   * The feature id for the '<em><b>Spkv</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int F__SPKV = 4;

  /**
   * The number of structural features of the '<em>F</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int F_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link sysml.dml.impl.SImpl <em>S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.SImpl
   * @see sysml.dml.impl.DmlPackageImpl#getS()
   * @generated
   */
  int S = 2;

  /**
   * The feature id for the '<em><b>Src</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__SRC = 0;

  /**
   * The feature id for the '<em><b>Srcid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__SRCID = 1;

  /**
   * The feature id for the '<em><b>Cwd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__CWD = 2;

  /**
   * The feature id for the '<em><b>Ife</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__IFE = 3;

  /**
   * The feature id for the '<em><b>Is</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__IS = 4;

  /**
   * The feature id for the '<em><b>Es</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__ES = 5;

  /**
   * The feature id for the '<em><b>Fp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__FP = 6;

  /**
   * The feature id for the '<em><b>P</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__P = 7;

  /**
   * The feature id for the '<em><b>S</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__S = 8;

  /**
   * The feature id for the '<em><b>Pf</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__PF = 9;

  /**
   * The feature id for the '<em><b>We</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__WE = 10;

  /**
   * The feature id for the '<em><b>Di</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__DI = 11;

  /**
   * The feature id for the '<em><b>Fc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__FC = 12;

  /**
   * The feature id for the '<em><b>Lhsdi</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__LHSDI = 13;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__E = 14;

  /**
   * The number of structural features of the '<em>S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S_FEATURE_COUNT = 15;

  /**
   * The meta object id for the '{@link sysml.dml.impl.FCImpl <em>FC</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.FCImpl
   * @see sysml.dml.impl.DmlPackageImpl#getFC()
   * @generated
   */
  int FC = 3;

  /**
   * The feature id for the '<em><b>Bif</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FC__BIF = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FC__ID = 1;

  /**
   * The feature id for the '<em><b>Pe</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FC__PE = 2;

  /**
   * The number of structural features of the '<em>FC</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FC_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link sysml.dml.impl.BSImpl <em>BS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.BSImpl
   * @see sysml.dml.impl.DmlPackageImpl#getBS()
   * @generated
   */
  int BS = 4;

  /**
   * The feature id for the '<em><b>Single S</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BS__SINGLE_S = 0;

  /**
   * The feature id for the '<em><b>S</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BS__S = 1;

  /**
   * The number of structural features of the '<em>BS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link sysml.dml.impl.FPImpl <em>FP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.FPImpl
   * @see sysml.dml.impl.DmlPackageImpl#getFP()
   * @generated
   */
  int FP = 5;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FP__ID = 0;

  /**
   * The feature id for the '<em><b>Is</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FP__IS = 1;

  /**
   * The number of structural features of the '<em>FP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link sysml.dml.impl.PARFORPARAMSImpl <em>PARFORPARAMS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.PARFORPARAMSImpl
   * @see sysml.dml.impl.DmlPackageImpl#getPARFORPARAMS()
   * @generated
   */
  int PARFORPARAMS = 6;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARFORPARAMS__PARAMS = 0;

  /**
   * The number of structural features of the '<em>PARFORPARAMS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARFORPARAMS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link sysml.dml.impl.DIImpl <em>DI</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.DIImpl
   * @see sysml.dml.impl.DmlPackageImpl#getDI()
   * @generated
   */
  int DI = 7;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DI__ID = 0;

  /**
   * The feature id for the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DI__B = 1;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DI__E = 2;

  /**
   * The feature id for the '<em><b>Clid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DI__CLID = 3;

  /**
   * The feature id for the '<em><b>Cln</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DI__CLN = 4;

  /**
   * The number of structural features of the '<em>DI</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DI_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link sysml.dml.impl.ISImpl <em>IS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.ISImpl
   * @see sysml.dml.impl.DmlPackageImpl#getIS()
   * @generated
   */
  int IS = 8;

  /**
   * The feature id for the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS__E1 = 0;

  /**
   * The feature id for the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS__E2 = 1;

  /**
   * The number of structural features of the '<em>IS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link sysml.dml.impl.PLImpl <em>PL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.PLImpl
   * @see sysml.dml.impl.DmlPackageImpl#getPL()
   * @generated
   */
  int PL = 9;

  /**
   * The feature id for the '<em><b>T</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PL__T = 0;

  /**
   * The number of structural features of the '<em>PL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link sysml.dml.impl.EImpl <em>E</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.EImpl
   * @see sysml.dml.impl.DmlPackageImpl#getE()
   * @generated
   */
  int E = 10;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int E__OP = 0;

  /**
   * The feature id for the '<em><b>T1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int E__T1 = 1;

  /**
   * The feature id for the '<em><b>T2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int E__T2 = 2;

  /**
   * The number of structural features of the '<em>E</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int E_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link sysml.dml.impl.TEImpl <em>TE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.TEImpl
   * @see sysml.dml.impl.DmlPackageImpl#getTE()
   * @generated
   */
  int TE = 11;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TE__E = 0;

  /**
   * The feature id for the '<em><b>I</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TE__I = 1;

  /**
   * The feature id for the '<em><b>D</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TE__D = 2;

  /**
   * The feature id for the '<em><b>S</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TE__S = 3;

  /**
   * The feature id for the '<em><b>B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TE__B = 4;

  /**
   * The feature id for the '<em><b>F</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TE__F = 5;

  /**
   * The feature id for the '<em><b>Di</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TE__DI = 6;

  /**
   * The number of structural features of the '<em>TE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link sysml.dml.impl.SPKVImpl <em>SPKV</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.SPKVImpl
   * @see sysml.dml.impl.DmlPackageImpl#getSPKV()
   * @generated
   */
  int SPKV = 12;

  /**
   * The feature id for the '<em><b>K</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPKV__K = 0;

  /**
   * The feature id for the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPKV__V = 1;

  /**
   * The number of structural features of the '<em>SPKV</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPKV_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link sysml.dml.impl.PEImpl <em>PE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.PEImpl
   * @see sysml.dml.impl.DmlPackageImpl#getPE()
   * @generated
   */
  int PE = 13;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PE__ID = 0;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PE__E = 1;

  /**
   * The number of structural features of the '<em>PE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link sysml.dml.impl.TANImpl <em>TAN</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.TANImpl
   * @see sysml.dml.impl.DmlPackageImpl#getTAN()
   * @generated
   */
  int TAN = 14;

  /**
   * The feature id for the '<em><b>T</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAN__T = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAN__NAME = 1;

  /**
   * The number of structural features of the '<em>TAN</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link sysml.dml.impl.IDImpl <em>ID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sysml.dml.impl.IDImpl
   * @see sysml.dml.impl.DmlPackageImpl#getID()
   * @generated
   */
  int ID = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ID__NAME = 0;

  /**
   * The number of structural features of the '<em>ID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ID_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link sysml.dml.D <em>D</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>D</em>'.
   * @see sysml.dml.D
   * @generated
   */
  EClass getD();

  /**
   * Returns the meta object for the containment reference list '{@link sysml.dml.D#getF <em>F</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>F</em>'.
   * @see sysml.dml.D#getF()
   * @see #getD()
   * @generated
   */
  EReference getD_F();

  /**
   * Returns the meta object for the containment reference list '{@link sysml.dml.D#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>S</em>'.
   * @see sysml.dml.D#getS()
   * @see #getD()
   * @generated
   */
  EReference getD_S();

  /**
   * Returns the meta object for class '{@link sysml.dml.F <em>F</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>F</em>'.
   * @see sysml.dml.F
   * @generated
   */
  EClass getF();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.F#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see sysml.dml.F#getName()
   * @see #getF()
   * @generated
   */
  EReference getF_Name();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.F#getI <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>I</em>'.
   * @see sysml.dml.F#getI()
   * @see #getF()
   * @generated
   */
  EReference getF_I();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.F#getR <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>R</em>'.
   * @see sysml.dml.F#getR()
   * @see #getF()
   * @generated
   */
  EReference getF_R();

  /**
   * Returns the meta object for the containment reference list '{@link sysml.dml.F#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>S</em>'.
   * @see sysml.dml.F#getS()
   * @see #getF()
   * @generated
   */
  EReference getF_S();

  /**
   * Returns the meta object for the containment reference list '{@link sysml.dml.F#getSpkv <em>Spkv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Spkv</em>'.
   * @see sysml.dml.F#getSpkv()
   * @see #getF()
   * @generated
   */
  EReference getF_Spkv();

  /**
   * Returns the meta object for class '{@link sysml.dml.S <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>S</em>'.
   * @see sysml.dml.S
   * @generated
   */
  EClass getS();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.S#getSrc <em>Src</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Src</em>'.
   * @see sysml.dml.S#getSrc()
   * @see #getS()
   * @generated
   */
  EAttribute getS_Src();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.S#getSrcid <em>Srcid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Srcid</em>'.
   * @see sysml.dml.S#getSrcid()
   * @see #getS()
   * @generated
   */
  EReference getS_Srcid();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.S#getCwd <em>Cwd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cwd</em>'.
   * @see sysml.dml.S#getCwd()
   * @see #getS()
   * @generated
   */
  EAttribute getS_Cwd();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.S#getIfe <em>Ife</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ife</em>'.
   * @see sysml.dml.S#getIfe()
   * @see #getS()
   * @generated
   */
  EReference getS_Ife();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.S#getIs <em>Is</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Is</em>'.
   * @see sysml.dml.S#getIs()
   * @see #getS()
   * @generated
   */
  EReference getS_Is();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.S#getEs <em>Es</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Es</em>'.
   * @see sysml.dml.S#getEs()
   * @see #getS()
   * @generated
   */
  EReference getS_Es();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.S#getFp <em>Fp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fp</em>'.
   * @see sysml.dml.S#getFp()
   * @see #getS()
   * @generated
   */
  EReference getS_Fp();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.S#getP <em>P</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>P</em>'.
   * @see sysml.dml.S#getP()
   * @see #getS()
   * @generated
   */
  EReference getS_P();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.S#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>S</em>'.
   * @see sysml.dml.S#getS()
   * @see #getS()
   * @generated
   */
  EReference getS_S();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.S#getPf <em>Pf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pf</em>'.
   * @see sysml.dml.S#getPf()
   * @see #getS()
   * @generated
   */
  EReference getS_Pf();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.S#getWe <em>We</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>We</em>'.
   * @see sysml.dml.S#getWe()
   * @see #getS()
   * @generated
   */
  EReference getS_We();

  /**
   * Returns the meta object for the containment reference list '{@link sysml.dml.S#getDi <em>Di</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Di</em>'.
   * @see sysml.dml.S#getDi()
   * @see #getS()
   * @generated
   */
  EReference getS_Di();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.S#getFc <em>Fc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fc</em>'.
   * @see sysml.dml.S#getFc()
   * @see #getS()
   * @generated
   */
  EReference getS_Fc();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.S#getLhsdi <em>Lhsdi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhsdi</em>'.
   * @see sysml.dml.S#getLhsdi()
   * @see #getS()
   * @generated
   */
  EReference getS_Lhsdi();

  /**
   * Returns the meta object for the containment reference list '{@link sysml.dml.S#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>E</em>'.
   * @see sysml.dml.S#getE()
   * @see #getS()
   * @generated
   */
  EReference getS_E();

  /**
   * Returns the meta object for class '{@link sysml.dml.FC <em>FC</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FC</em>'.
   * @see sysml.dml.FC
   * @generated
   */
  EClass getFC();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.FC#getBif <em>Bif</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bif</em>'.
   * @see sysml.dml.FC#getBif()
   * @see #getFC()
   * @generated
   */
  EAttribute getFC_Bif();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.FC#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see sysml.dml.FC#getId()
   * @see #getFC()
   * @generated
   */
  EReference getFC_Id();

  /**
   * Returns the meta object for the containment reference list '{@link sysml.dml.FC#getPe <em>Pe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pe</em>'.
   * @see sysml.dml.FC#getPe()
   * @see #getFC()
   * @generated
   */
  EReference getFC_Pe();

  /**
   * Returns the meta object for class '{@link sysml.dml.BS <em>BS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BS</em>'.
   * @see sysml.dml.BS
   * @generated
   */
  EClass getBS();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.BS#getSingleS <em>Single S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Single S</em>'.
   * @see sysml.dml.BS#getSingleS()
   * @see #getBS()
   * @generated
   */
  EReference getBS_SingleS();

  /**
   * Returns the meta object for the containment reference list '{@link sysml.dml.BS#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>S</em>'.
   * @see sysml.dml.BS#getS()
   * @see #getBS()
   * @generated
   */
  EReference getBS_S();

  /**
   * Returns the meta object for class '{@link sysml.dml.FP <em>FP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FP</em>'.
   * @see sysml.dml.FP
   * @generated
   */
  EClass getFP();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.FP#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see sysml.dml.FP#getId()
   * @see #getFP()
   * @generated
   */
  EReference getFP_Id();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.FP#getIs <em>Is</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Is</em>'.
   * @see sysml.dml.FP#getIs()
   * @see #getFP()
   * @generated
   */
  EReference getFP_Is();

  /**
   * Returns the meta object for class '{@link sysml.dml.PARFORPARAMS <em>PARFORPARAMS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PARFORPARAMS</em>'.
   * @see sysml.dml.PARFORPARAMS
   * @generated
   */
  EClass getPARFORPARAMS();

  /**
   * Returns the meta object for the attribute list '{@link sysml.dml.PARFORPARAMS#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see sysml.dml.PARFORPARAMS#getParams()
   * @see #getPARFORPARAMS()
   * @generated
   */
  EAttribute getPARFORPARAMS_Params();

  /**
   * Returns the meta object for class '{@link sysml.dml.DI <em>DI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DI</em>'.
   * @see sysml.dml.DI
   * @generated
   */
  EClass getDI();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.DI#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see sysml.dml.DI#getId()
   * @see #getDI()
   * @generated
   */
  EReference getDI_Id();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.DI#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>B</em>'.
   * @see sysml.dml.DI#getB()
   * @see #getDI()
   * @generated
   */
  EReference getDI_B();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.DI#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see sysml.dml.DI#getE()
   * @see #getDI()
   * @generated
   */
  EReference getDI_E();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.DI#getClid <em>Clid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Clid</em>'.
   * @see sysml.dml.DI#getClid()
   * @see #getDI()
   * @generated
   */
  EAttribute getDI_Clid();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.DI#getCln <em>Cln</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cln</em>'.
   * @see sysml.dml.DI#getCln()
   * @see #getDI()
   * @generated
   */
  EAttribute getDI_Cln();

  /**
   * Returns the meta object for class '{@link sysml.dml.IS <em>IS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IS</em>'.
   * @see sysml.dml.IS
   * @generated
   */
  EClass getIS();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.IS#getE1 <em>E1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E1</em>'.
   * @see sysml.dml.IS#getE1()
   * @see #getIS()
   * @generated
   */
  EReference getIS_E1();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.IS#getE2 <em>E2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E2</em>'.
   * @see sysml.dml.IS#getE2()
   * @see #getIS()
   * @generated
   */
  EReference getIS_E2();

  /**
   * Returns the meta object for class '{@link sysml.dml.PL <em>PL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PL</em>'.
   * @see sysml.dml.PL
   * @generated
   */
  EClass getPL();

  /**
   * Returns the meta object for the containment reference list '{@link sysml.dml.PL#getT <em>T</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>T</em>'.
   * @see sysml.dml.PL#getT()
   * @see #getPL()
   * @generated
   */
  EReference getPL_T();

  /**
   * Returns the meta object for class '{@link sysml.dml.E <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>E</em>'.
   * @see sysml.dml.E
   * @generated
   */
  EClass getE();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.E#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see sysml.dml.E#getOp()
   * @see #getE()
   * @generated
   */
  EAttribute getE_Op();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.E#getT1 <em>T1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>T1</em>'.
   * @see sysml.dml.E#getT1()
   * @see #getE()
   * @generated
   */
  EReference getE_T1();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.E#getT2 <em>T2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>T2</em>'.
   * @see sysml.dml.E#getT2()
   * @see #getE()
   * @generated
   */
  EReference getE_T2();

  /**
   * Returns the meta object for class '{@link sysml.dml.TE <em>TE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TE</em>'.
   * @see sysml.dml.TE
   * @generated
   */
  EClass getTE();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.TE#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see sysml.dml.TE#getE()
   * @see #getTE()
   * @generated
   */
  EReference getTE_E();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.TE#getI <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>I</em>'.
   * @see sysml.dml.TE#getI()
   * @see #getTE()
   * @generated
   */
  EAttribute getTE_I();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.TE#getD <em>D</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>D</em>'.
   * @see sysml.dml.TE#getD()
   * @see #getTE()
   * @generated
   */
  EAttribute getTE_D();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.TE#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>S</em>'.
   * @see sysml.dml.TE#getS()
   * @see #getTE()
   * @generated
   */
  EAttribute getTE_S();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.TE#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>B</em>'.
   * @see sysml.dml.TE#getB()
   * @see #getTE()
   * @generated
   */
  EAttribute getTE_B();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.TE#getF <em>F</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>F</em>'.
   * @see sysml.dml.TE#getF()
   * @see #getTE()
   * @generated
   */
  EReference getTE_F();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.TE#getDi <em>Di</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Di</em>'.
   * @see sysml.dml.TE#getDi()
   * @see #getTE()
   * @generated
   */
  EReference getTE_Di();

  /**
   * Returns the meta object for class '{@link sysml.dml.SPKV <em>SPKV</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SPKV</em>'.
   * @see sysml.dml.SPKV
   * @generated
   */
  EClass getSPKV();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.SPKV#getK <em>K</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>K</em>'.
   * @see sysml.dml.SPKV#getK()
   * @see #getSPKV()
   * @generated
   */
  EReference getSPKV_K();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.SPKV#getV <em>V</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>V</em>'.
   * @see sysml.dml.SPKV#getV()
   * @see #getSPKV()
   * @generated
   */
  EAttribute getSPKV_V();

  /**
   * Returns the meta object for class '{@link sysml.dml.PE <em>PE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PE</em>'.
   * @see sysml.dml.PE
   * @generated
   */
  EClass getPE();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.PE#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see sysml.dml.PE#getId()
   * @see #getPE()
   * @generated
   */
  EReference getPE_Id();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.PE#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see sysml.dml.PE#getE()
   * @see #getPE()
   * @generated
   */
  EReference getPE_E();

  /**
   * Returns the meta object for class '{@link sysml.dml.TAN <em>TAN</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TAN</em>'.
   * @see sysml.dml.TAN
   * @generated
   */
  EClass getTAN();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.TAN#getT <em>T</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>T</em>'.
   * @see sysml.dml.TAN#getT()
   * @see #getTAN()
   * @generated
   */
  EAttribute getTAN_T();

  /**
   * Returns the meta object for the containment reference '{@link sysml.dml.TAN#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see sysml.dml.TAN#getName()
   * @see #getTAN()
   * @generated
   */
  EReference getTAN_Name();

  /**
   * Returns the meta object for class '{@link sysml.dml.ID <em>ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ID</em>'.
   * @see sysml.dml.ID
   * @generated
   */
  EClass getID();

  /**
   * Returns the meta object for the attribute '{@link sysml.dml.ID#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see sysml.dml.ID#getName()
   * @see #getID()
   * @generated
   */
  EAttribute getID_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DmlFactory getDmlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link sysml.dml.impl.DImpl <em>D</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.DImpl
     * @see sysml.dml.impl.DmlPackageImpl#getD()
     * @generated
     */
    EClass D = eINSTANCE.getD();

    /**
     * The meta object literal for the '<em><b>F</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference D__F = eINSTANCE.getD_F();

    /**
     * The meta object literal for the '<em><b>S</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference D__S = eINSTANCE.getD_S();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.FImpl <em>F</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.FImpl
     * @see sysml.dml.impl.DmlPackageImpl#getF()
     * @generated
     */
    EClass F = eINSTANCE.getF();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference F__NAME = eINSTANCE.getF_Name();

    /**
     * The meta object literal for the '<em><b>I</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference F__I = eINSTANCE.getF_I();

    /**
     * The meta object literal for the '<em><b>R</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference F__R = eINSTANCE.getF_R();

    /**
     * The meta object literal for the '<em><b>S</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference F__S = eINSTANCE.getF_S();

    /**
     * The meta object literal for the '<em><b>Spkv</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference F__SPKV = eINSTANCE.getF_Spkv();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.SImpl <em>S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.SImpl
     * @see sysml.dml.impl.DmlPackageImpl#getS()
     * @generated
     */
    EClass S = eINSTANCE.getS();

    /**
     * The meta object literal for the '<em><b>Src</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute S__SRC = eINSTANCE.getS_Src();

    /**
     * The meta object literal for the '<em><b>Srcid</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__SRCID = eINSTANCE.getS_Srcid();

    /**
     * The meta object literal for the '<em><b>Cwd</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute S__CWD = eINSTANCE.getS_Cwd();

    /**
     * The meta object literal for the '<em><b>Ife</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__IFE = eINSTANCE.getS_Ife();

    /**
     * The meta object literal for the '<em><b>Is</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__IS = eINSTANCE.getS_Is();

    /**
     * The meta object literal for the '<em><b>Es</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__ES = eINSTANCE.getS_Es();

    /**
     * The meta object literal for the '<em><b>Fp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__FP = eINSTANCE.getS_Fp();

    /**
     * The meta object literal for the '<em><b>P</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__P = eINSTANCE.getS_P();

    /**
     * The meta object literal for the '<em><b>S</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__S = eINSTANCE.getS_S();

    /**
     * The meta object literal for the '<em><b>Pf</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__PF = eINSTANCE.getS_Pf();

    /**
     * The meta object literal for the '<em><b>We</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__WE = eINSTANCE.getS_We();

    /**
     * The meta object literal for the '<em><b>Di</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__DI = eINSTANCE.getS_Di();

    /**
     * The meta object literal for the '<em><b>Fc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__FC = eINSTANCE.getS_Fc();

    /**
     * The meta object literal for the '<em><b>Lhsdi</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__LHSDI = eINSTANCE.getS_Lhsdi();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__E = eINSTANCE.getS_E();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.FCImpl <em>FC</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.FCImpl
     * @see sysml.dml.impl.DmlPackageImpl#getFC()
     * @generated
     */
    EClass FC = eINSTANCE.getFC();

    /**
     * The meta object literal for the '<em><b>Bif</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FC__BIF = eINSTANCE.getFC_Bif();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FC__ID = eINSTANCE.getFC_Id();

    /**
     * The meta object literal for the '<em><b>Pe</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FC__PE = eINSTANCE.getFC_Pe();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.BSImpl <em>BS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.BSImpl
     * @see sysml.dml.impl.DmlPackageImpl#getBS()
     * @generated
     */
    EClass BS = eINSTANCE.getBS();

    /**
     * The meta object literal for the '<em><b>Single S</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BS__SINGLE_S = eINSTANCE.getBS_SingleS();

    /**
     * The meta object literal for the '<em><b>S</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BS__S = eINSTANCE.getBS_S();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.FPImpl <em>FP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.FPImpl
     * @see sysml.dml.impl.DmlPackageImpl#getFP()
     * @generated
     */
    EClass FP = eINSTANCE.getFP();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FP__ID = eINSTANCE.getFP_Id();

    /**
     * The meta object literal for the '<em><b>Is</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FP__IS = eINSTANCE.getFP_Is();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.PARFORPARAMSImpl <em>PARFORPARAMS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.PARFORPARAMSImpl
     * @see sysml.dml.impl.DmlPackageImpl#getPARFORPARAMS()
     * @generated
     */
    EClass PARFORPARAMS = eINSTANCE.getPARFORPARAMS();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARFORPARAMS__PARAMS = eINSTANCE.getPARFORPARAMS_Params();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.DIImpl <em>DI</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.DIImpl
     * @see sysml.dml.impl.DmlPackageImpl#getDI()
     * @generated
     */
    EClass DI = eINSTANCE.getDI();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DI__ID = eINSTANCE.getDI_Id();

    /**
     * The meta object literal for the '<em><b>B</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DI__B = eINSTANCE.getDI_B();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DI__E = eINSTANCE.getDI_E();

    /**
     * The meta object literal for the '<em><b>Clid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DI__CLID = eINSTANCE.getDI_Clid();

    /**
     * The meta object literal for the '<em><b>Cln</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DI__CLN = eINSTANCE.getDI_Cln();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.ISImpl <em>IS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.ISImpl
     * @see sysml.dml.impl.DmlPackageImpl#getIS()
     * @generated
     */
    EClass IS = eINSTANCE.getIS();

    /**
     * The meta object literal for the '<em><b>E1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS__E1 = eINSTANCE.getIS_E1();

    /**
     * The meta object literal for the '<em><b>E2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS__E2 = eINSTANCE.getIS_E2();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.PLImpl <em>PL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.PLImpl
     * @see sysml.dml.impl.DmlPackageImpl#getPL()
     * @generated
     */
    EClass PL = eINSTANCE.getPL();

    /**
     * The meta object literal for the '<em><b>T</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PL__T = eINSTANCE.getPL_T();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.EImpl <em>E</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.EImpl
     * @see sysml.dml.impl.DmlPackageImpl#getE()
     * @generated
     */
    EClass E = eINSTANCE.getE();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute E__OP = eINSTANCE.getE_Op();

    /**
     * The meta object literal for the '<em><b>T1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference E__T1 = eINSTANCE.getE_T1();

    /**
     * The meta object literal for the '<em><b>T2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference E__T2 = eINSTANCE.getE_T2();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.TEImpl <em>TE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.TEImpl
     * @see sysml.dml.impl.DmlPackageImpl#getTE()
     * @generated
     */
    EClass TE = eINSTANCE.getTE();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TE__E = eINSTANCE.getTE_E();

    /**
     * The meta object literal for the '<em><b>I</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TE__I = eINSTANCE.getTE_I();

    /**
     * The meta object literal for the '<em><b>D</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TE__D = eINSTANCE.getTE_D();

    /**
     * The meta object literal for the '<em><b>S</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TE__S = eINSTANCE.getTE_S();

    /**
     * The meta object literal for the '<em><b>B</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TE__B = eINSTANCE.getTE_B();

    /**
     * The meta object literal for the '<em><b>F</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TE__F = eINSTANCE.getTE_F();

    /**
     * The meta object literal for the '<em><b>Di</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TE__DI = eINSTANCE.getTE_Di();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.SPKVImpl <em>SPKV</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.SPKVImpl
     * @see sysml.dml.impl.DmlPackageImpl#getSPKV()
     * @generated
     */
    EClass SPKV = eINSTANCE.getSPKV();

    /**
     * The meta object literal for the '<em><b>K</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPKV__K = eINSTANCE.getSPKV_K();

    /**
     * The meta object literal for the '<em><b>V</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPKV__V = eINSTANCE.getSPKV_V();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.PEImpl <em>PE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.PEImpl
     * @see sysml.dml.impl.DmlPackageImpl#getPE()
     * @generated
     */
    EClass PE = eINSTANCE.getPE();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PE__ID = eINSTANCE.getPE_Id();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PE__E = eINSTANCE.getPE_E();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.TANImpl <em>TAN</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.TANImpl
     * @see sysml.dml.impl.DmlPackageImpl#getTAN()
     * @generated
     */
    EClass TAN = eINSTANCE.getTAN();

    /**
     * The meta object literal for the '<em><b>T</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAN__T = eINSTANCE.getTAN_T();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAN__NAME = eINSTANCE.getTAN_Name();

    /**
     * The meta object literal for the '{@link sysml.dml.impl.IDImpl <em>ID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sysml.dml.impl.IDImpl
     * @see sysml.dml.impl.DmlPackageImpl#getID()
     * @generated
     */
    EClass ID = eINSTANCE.getID();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ID__NAME = eINSTANCE.getID_Name();

  }

} //DmlPackage
