/**
 * generated by Xtext 2.9.0
 */
package sysml.dml;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>F</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sysml.dml.F#getName <em>Name</em>}</li>
 *   <li>{@link sysml.dml.F#getI <em>I</em>}</li>
 *   <li>{@link sysml.dml.F#getR <em>R</em>}</li>
 *   <li>{@link sysml.dml.F#getS <em>S</em>}</li>
 *   <li>{@link sysml.dml.F#getSpkv <em>Spkv</em>}</li>
 * </ul>
 *
 * @see sysml.dml.DmlPackage#getF()
 * @model
 * @generated
 */
public interface F extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(ID)
   * @see sysml.dml.DmlPackage#getF_Name()
   * @model containment="true"
   * @generated
   */
  ID getName();

  /**
   * Sets the value of the '{@link sysml.dml.F#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(ID value);

  /**
   * Returns the value of the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>I</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>I</em>' containment reference.
   * @see #setI(PL)
   * @see sysml.dml.DmlPackage#getF_I()
   * @model containment="true"
   * @generated
   */
  PL getI();

  /**
   * Sets the value of the '{@link sysml.dml.F#getI <em>I</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>I</em>' containment reference.
   * @see #getI()
   * @generated
   */
  void setI(PL value);

  /**
   * Returns the value of the '<em><b>R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>R</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' containment reference.
   * @see #setR(PL)
   * @see sysml.dml.DmlPackage#getF_R()
   * @model containment="true"
   * @generated
   */
  PL getR();

  /**
   * Sets the value of the '{@link sysml.dml.F#getR <em>R</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' containment reference.
   * @see #getR()
   * @generated
   */
  void setR(PL value);

  /**
   * Returns the value of the '<em><b>S</b></em>' containment reference list.
   * The list contents are of type {@link sysml.dml.S}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>S</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' containment reference list.
   * @see sysml.dml.DmlPackage#getF_S()
   * @model containment="true"
   * @generated
   */
  EList<S> getS();

  /**
   * Returns the value of the '<em><b>Spkv</b></em>' containment reference list.
   * The list contents are of type {@link sysml.dml.SPKV}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Spkv</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spkv</em>' containment reference list.
   * @see sysml.dml.DmlPackage#getF_Spkv()
   * @model containment="true"
   * @generated
   */
  EList<SPKV> getSpkv();

} // F
