/**
 * generated by Xtext 2.9.0
 */
package sysml.dml;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FC</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sysml.dml.FC#getBif <em>Bif</em>}</li>
 *   <li>{@link sysml.dml.FC#getId <em>Id</em>}</li>
 *   <li>{@link sysml.dml.FC#getPe <em>Pe</em>}</li>
 * </ul>
 *
 * @see sysml.dml.DmlPackage#getFC()
 * @model
 * @generated
 */
public interface FC extends EObject
{
  /**
   * Returns the value of the '<em><b>Bif</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bif</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bif</em>' attribute.
   * @see #setBif(String)
   * @see sysml.dml.DmlPackage#getFC_Bif()
   * @model
   * @generated
   */
  String getBif();

  /**
   * Sets the value of the '{@link sysml.dml.FC#getBif <em>Bif</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bif</em>' attribute.
   * @see #getBif()
   * @generated
   */
  void setBif(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' containment reference.
   * @see #setId(ID)
   * @see sysml.dml.DmlPackage#getFC_Id()
   * @model containment="true"
   * @generated
   */
  ID getId();

  /**
   * Sets the value of the '{@link sysml.dml.FC#getId <em>Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' containment reference.
   * @see #getId()
   * @generated
   */
  void setId(ID value);

  /**
   * Returns the value of the '<em><b>Pe</b></em>' containment reference list.
   * The list contents are of type {@link sysml.dml.PE}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pe</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pe</em>' containment reference list.
   * @see sysml.dml.DmlPackage#getFC_Pe()
   * @model containment="true"
   * @generated
   */
  EList<PE> getPe();

} // FC
