/**
 * generated by Xtext 2.9.0
 */
package sysml.dml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sysml.dml.FP#getId <em>Id</em>}</li>
 *   <li>{@link sysml.dml.FP#getIs <em>Is</em>}</li>
 * </ul>
 *
 * @see sysml.dml.DmlPackage#getFP()
 * @model
 * @generated
 */
public interface FP extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' containment reference.
   * @see #setId(ID)
   * @see sysml.dml.DmlPackage#getFP_Id()
   * @model containment="true"
   * @generated
   */
  ID getId();

  /**
   * Sets the value of the '{@link sysml.dml.FP#getId <em>Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' containment reference.
   * @see #getId()
   * @generated
   */
  void setId(ID value);

  /**
   * Returns the value of the '<em><b>Is</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is</em>' containment reference.
   * @see #setIs(IS)
   * @see sysml.dml.DmlPackage#getFP_Is()
   * @model containment="true"
   * @generated
   */
  IS getIs();

  /**
   * Sets the value of the '{@link sysml.dml.FP#getIs <em>Is</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is</em>' containment reference.
   * @see #getIs()
   * @generated
   */
  void setIs(IS value);

} // FP
