/**
 * generated by Xtext 2.9.0
 */
package sysml.dml;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PARFORPARAMS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sysml.dml.PARFORPARAMS#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see sysml.dml.DmlPackage#getPARFORPARAMS()
 * @model
 * @generated
 */
public interface PARFORPARAMS extends EObject
{
  /**
   * Returns the value of the '<em><b>Params</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' attribute list.
   * @see sysml.dml.DmlPackage#getPARFORPARAMS_Params()
   * @model unique="false"
   * @generated
   */
  EList<String> getParams();

} // PARFORPARAMS
