/**
 * generated by Xtext 2.9.0
 */
package sysml.dml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sysml.dml.PE#getId <em>Id</em>}</li>
 *   <li>{@link sysml.dml.PE#getE <em>E</em>}</li>
 * </ul>
 *
 * @see sysml.dml.DmlPackage#getPE()
 * @model
 * @generated
 */
public interface PE extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' containment reference.
   * @see #setId(ID)
   * @see sysml.dml.DmlPackage#getPE_Id()
   * @model containment="true"
   * @generated
   */
  ID getId();

  /**
   * Sets the value of the '{@link sysml.dml.PE#getId <em>Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' containment reference.
   * @see #getId()
   * @generated
   */
  void setId(ID value);

  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>E</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference.
   * @see #setE(E)
   * @see sysml.dml.DmlPackage#getPE_E()
   * @model containment="true"
   * @generated
   */
  E getE();

  /**
   * Sets the value of the '{@link sysml.dml.PE#getE <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' containment reference.
   * @see #getE()
   * @generated
   */
  void setE(E value);

} // PE
