/**
 * generated by Xtext 2.9.0
 */
package sysml.dml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TAN</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sysml.dml.TAN#getT <em>T</em>}</li>
 *   <li>{@link sysml.dml.TAN#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see sysml.dml.DmlPackage#getTAN()
 * @model
 * @generated
 */
public interface TAN extends EObject
{
  /**
   * Returns the value of the '<em><b>T</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>T</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>T</em>' attribute.
   * @see #setT(String)
   * @see sysml.dml.DmlPackage#getTAN_T()
   * @model
   * @generated
   */
  String getT();

  /**
   * Sets the value of the '{@link sysml.dml.TAN#getT <em>T</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>T</em>' attribute.
   * @see #getT()
   * @generated
   */
  void setT(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(ID)
   * @see sysml.dml.DmlPackage#getTAN_Name()
   * @model containment="true"
   * @generated
   */
  ID getName();

  /**
   * Sets the value of the '{@link sysml.dml.TAN#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(ID value);

} // TAN
