/**
 * generated by Xtext 2.9.0
 */
package sysml.dml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sysml.dml.TE#getE <em>E</em>}</li>
 *   <li>{@link sysml.dml.TE#getI <em>I</em>}</li>
 *   <li>{@link sysml.dml.TE#getD <em>D</em>}</li>
 *   <li>{@link sysml.dml.TE#getS <em>S</em>}</li>
 *   <li>{@link sysml.dml.TE#getB <em>B</em>}</li>
 *   <li>{@link sysml.dml.TE#getF <em>F</em>}</li>
 *   <li>{@link sysml.dml.TE#getDi <em>Di</em>}</li>
 * </ul>
 *
 * @see sysml.dml.DmlPackage#getTE()
 * @model
 * @generated
 */
public interface TE extends EObject
{
  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>E</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference.
   * @see #setE(E)
   * @see sysml.dml.DmlPackage#getTE_E()
   * @model containment="true"
   * @generated
   */
  E getE();

  /**
   * Sets the value of the '{@link sysml.dml.TE#getE <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' containment reference.
   * @see #getE()
   * @generated
   */
  void setE(E value);

  /**
   * Returns the value of the '<em><b>I</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>I</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>I</em>' attribute.
   * @see #setI(int)
   * @see sysml.dml.DmlPackage#getTE_I()
   * @model
   * @generated
   */
  int getI();

  /**
   * Sets the value of the '{@link sysml.dml.TE#getI <em>I</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>I</em>' attribute.
   * @see #getI()
   * @generated
   */
  void setI(int value);

  /**
   * Returns the value of the '<em><b>D</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>D</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>D</em>' attribute.
   * @see #setD(double)
   * @see sysml.dml.DmlPackage#getTE_D()
   * @model
   * @generated
   */
  double getD();

  /**
   * Sets the value of the '{@link sysml.dml.TE#getD <em>D</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>D</em>' attribute.
   * @see #getD()
   * @generated
   */
  void setD(double value);

  /**
   * Returns the value of the '<em><b>S</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>S</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' attribute.
   * @see #setS(String)
   * @see sysml.dml.DmlPackage#getTE_S()
   * @model
   * @generated
   */
  String getS();

  /**
   * Sets the value of the '{@link sysml.dml.TE#getS <em>S</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S</em>' attribute.
   * @see #getS()
   * @generated
   */
  void setS(String value);

  /**
   * Returns the value of the '<em><b>B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>B</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' attribute.
   * @see #setB(String)
   * @see sysml.dml.DmlPackage#getTE_B()
   * @model
   * @generated
   */
  String getB();

  /**
   * Sets the value of the '{@link sysml.dml.TE#getB <em>B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>B</em>' attribute.
   * @see #getB()
   * @generated
   */
  void setB(String value);

  /**
   * Returns the value of the '<em><b>F</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>F</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>F</em>' containment reference.
   * @see #setF(FC)
   * @see sysml.dml.DmlPackage#getTE_F()
   * @model containment="true"
   * @generated
   */
  FC getF();

  /**
   * Sets the value of the '{@link sysml.dml.TE#getF <em>F</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F</em>' containment reference.
   * @see #getF()
   * @generated
   */
  void setF(FC value);

  /**
   * Returns the value of the '<em><b>Di</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Di</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Di</em>' containment reference.
   * @see #setDi(DI)
   * @see sysml.dml.DmlPackage#getTE_Di()
   * @model containment="true"
   * @generated
   */
  DI getDi();

  /**
   * Sets the value of the '{@link sysml.dml.TE#getDi <em>Di</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Di</em>' containment reference.
   * @see #getDi()
   * @generated
   */
  void setDi(DI value);

} // TE
