/*
 * generated by Xtext 2.9.0
 */
package sysml.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import sysml.dml.ui.internal.DmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DmlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DmlActivator.getInstance().getInjector(DmlActivator.SYSML_DML);
	}
	
}
