/*
 * generated by Xtext 2.9.0
 */
package sysml.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.xtext.psi.impl.BaseXtextFile;
import sysml.idea.lang.DmlFileType;
import sysml.idea.lang.DmlLanguage;

public final class DmlFileImpl extends BaseXtextFile {

	public DmlFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, DmlLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return DmlFileType.INSTANCE;
	}
}
