/**
 * generated by Xtext 2.9.0
 */
package sysml.idea;

import sysml.idea.AbstractDmlIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class DmlIdeaModule extends AbstractDmlIdeaModule {
}
