/**
 * generated by Xtext 2.9.0
 */
package sysml.idea;

import com.google.inject.Injector;
import sysml.DmlStandaloneSetupGenerated;

@SuppressWarnings("all")
public class DmlStandaloneSetupIdea extends DmlStandaloneSetupGenerated {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from DmlIdeaModule to Module");
  }
}
