/*
 * generated by Xtext 2.9.0
 */
package sysml.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class DmlLanguage extends AbstractXtextLanguage {

	public static final DmlLanguage INSTANCE = new DmlLanguage();

	private DmlLanguage() {
		super("sysml.Dml");
	}

}
