/**
 * generated by Xtext 2.9.0
 */
package sysml.idea.completion;

import sysml.idea.completion.AbstractDmlCompletionContributor;
import sysml.idea.lang.DmlLanguage;

@SuppressWarnings("all")
public class DmlCompletionContributor extends AbstractDmlCompletionContributor {
  public DmlCompletionContributor() {
    this(DmlLanguage.INSTANCE);
  }
  
  public DmlCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
