/**
 * generated by Xtext 2.9.0
 */
package sysml.idea.highlighting;

import sysml.idea.highlighting.DmlBaseColorSettingsPage;

@SuppressWarnings("all")
public class DmlColorSettingsPage extends DmlBaseColorSettingsPage {
}
