/**
 * generated by Xtext 2.9.0
 */
package sysml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import sysml.ui.AbstractDmlUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DmlUiModule extends AbstractDmlUiModule {
  public DmlUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
