/**
 * generated by Xtext 2.9.0
 */
package sysml.idea.lang;

import sysml.idea.lang.AbstractDmlFileType;

@SuppressWarnings("all")
public class DmlFileType extends AbstractDmlFileType {
  public final static DmlFileType INSTANCE = new DmlFileType();
  
  public DmlFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(DmlLanguage) is undefined");
  }
}
