/*
 * generated by Xtext 2.9.0
 */
package sysml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DmlStandaloneSetup extends DmlStandaloneSetupGenerated {

	def static void doSetup() {
		new DmlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
