/*
 * generated by Xtext 2.9.0
 */
package sysml.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;
import sysml.idea.lang.DmlLanguage;

public class DmlCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public DmlCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(DmlLanguage.INSTANCE, psiModificationTracker);
	}

}
