/**
 * generated by Xtext 2.9.0
 */
package sysml.ui.contentassist;

import sysml.ui.contentassist.AbstractDmlProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DmlProposalProvider extends AbstractDmlProposalProvider {
}
