/*
 * generated by Xtext 2.9.0
 */
package sysml.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import sysml.idea.lang.DmlLanguage;

public class DmlFacetType extends AbstractFacetType<DmlFacetConfiguration> {

	public static final FacetTypeId<Facet<DmlFacetConfiguration>> TYPEID = new FacetTypeId<Facet<DmlFacetConfiguration>>("sysml.Dml");

	public DmlFacetType() {
		super(TYPEID, "sysml.Dml", "Dml");
		DmlLanguage.INSTANCE.injectMembers(this);
	}
}
