/*
 * generated by Xtext 2.9.0
 */
package sysml.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import sysml.dml.ui.internal.DmlActivator;

public class DmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DmlActivator.getInstance().getInjector("sysml.Dml");
	}

}
