/*
 * generated by Xtext 2.9.0
 */
package sysml.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;
import sysml.idea.lang.DmlLanguage;

public class DmlBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public DmlBaseColorSettingsPage() {
		DmlLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return DmlLanguage.INSTANCE.getDisplayName();
	}
}
