/*
 * generated by Xtext 2.9.0
 */
package sysml.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;
import sysml.idea.lang.DmlLanguage;

public class DmlSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public DmlSemanticHighlightVisitor() {
		DmlLanguage.INSTANCE.injectMembers(this);
	}
}
