/*
 * generated by Xtext 2.9.0
 */
package sysml.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sysml.parser.antlr.internal.InternalDmlParser;
import sysml.services.DmlGrammarAccess;

public class DmlParser extends AbstractAntlrParser {

	@Inject
	private DmlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDmlParser createParser(XtextTokenStream stream) {
		return new InternalDmlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "D";
	}

	public DmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
