/*
 * generated by Xtext 2.9.0
 */
package sysml.idea.lang.pom;

import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;
import sysml.idea.lang.DmlLanguage;

public class DmlPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public DmlPomDeclarationSearcher() {
		super(DmlLanguage.INSTANCE);
	}
}
