/*
 * generated by Xtext 2.9.0
 */
package sysml.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import sysml.ide.contentassist.antlr.internal.InternalDmlParser;
import sysml.services.DmlGrammarAccess;

public class DmlParser extends AbstractContentAssistParser {

	@Inject
	private DmlGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalDmlParser createParser() {
		InternalDmlParser result = new InternalDmlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDAccess().getAlternatives(), "rule__D__Alternatives");
					put(grammarAccess.getFAccess().getAlternatives(), "rule__F__Alternatives");
					put(grammarAccess.getSAccess().getAlternatives(), "rule__S__Alternatives");
					put(grammarAccess.getSAccess().getAlternatives_7_2(), "rule__S__Alternatives_7_2");
					put(grammarAccess.getFCAccess().getAlternatives_0(), "rule__FC__Alternatives_0");
					put(grammarAccess.getBSAccess().getAlternatives(), "rule__BS__Alternatives");
					put(grammarAccess.getPARAMSAccess().getAlternatives(), "rule__PARAMS__Alternatives");
					put(grammarAccess.getPARAMSAccess().getAlternatives_2_2(), "rule__PARAMS__Alternatives_2_2");
					put(grammarAccess.getPARAMSAccess().getAlternatives_3_2(), "rule__PARAMS__Alternatives_3_2");
					put(grammarAccess.getPARAMSAccess().getAlternatives_5_2(), "rule__PARAMS__Alternatives_5_2");
					put(grammarAccess.getPARAMSAccess().getAlternatives_6_2(), "rule__PARAMS__Alternatives_6_2");
					put(grammarAccess.getPARAMSAccess().getAlternatives_7_2(), "rule__PARAMS__Alternatives_7_2");
					put(grammarAccess.getDIAccess().getAlternatives(), "rule__DI__Alternatives");
					put(grammarAccess.getEAccess().getAlternatives(), "rule__E__Alternatives");
					put(grammarAccess.getEAccess().getOpAlternatives_0_0_0(), "rule__E__OpAlternatives_0_0_0");
					put(grammarAccess.getEAccess().getOpAlternatives_1_1_0_0(), "rule__E__OpAlternatives_1_1_0_0");
					put(grammarAccess.getTEAccess().getAlternatives(), "rule__TE__Alternatives");
					put(grammarAccess.getASAccess().getAlternatives(), "rule__AS__Alternatives");
					put(grammarAccess.getBIFAccess().getAlternatives(), "rule__BIF__Alternatives");
					put(grammarAccess.getMTAccess().getAlternatives(), "rule__MT__Alternatives");
					put(grammarAccess.getVTAccess().getAlternatives(), "rule__VT__Alternatives");
					put(grammarAccess.getDTAccess().getAlternatives(), "rule__DT__Alternatives");
					put(grammarAccess.getIDAccess().getAlternatives(), "rule__ID__Alternatives");
					put(grammarAccess.getFAccess().getGroup_0(), "rule__F__Group_0__0");
					put(grammarAccess.getFAccess().getGroup_0_6(), "rule__F__Group_0_6__0");
					put(grammarAccess.getFAccess().getGroup_1(), "rule__F__Group_1__0");
					put(grammarAccess.getFAccess().getGroup_1_6(), "rule__F__Group_1_6__0");
					put(grammarAccess.getFAccess().getGroup_1_10(), "rule__F__Group_1_10__0");
					put(grammarAccess.getFAccess().getGroup_1_10_1(), "rule__F__Group_1_10_1__0");
					put(grammarAccess.getSAccess().getGroup_0(), "rule__S__Group_0__0");
					put(grammarAccess.getSAccess().getGroup_1(), "rule__S__Group_1__0");
					put(grammarAccess.getSAccess().getGroup_2(), "rule__S__Group_2__0");
					put(grammarAccess.getSAccess().getGroup_2_5(), "rule__S__Group_2_5__0");
					put(grammarAccess.getSAccess().getGroup_3(), "rule__S__Group_3__0");
					put(grammarAccess.getSAccess().getGroup_4(), "rule__S__Group_4__0");
					put(grammarAccess.getSAccess().getGroup_5(), "rule__S__Group_5__0");
					put(grammarAccess.getSAccess().getGroup_6(), "rule__S__Group_6__0");
					put(grammarAccess.getSAccess().getGroup_6_2(), "rule__S__Group_6_2__0");
					put(grammarAccess.getSAccess().getGroup_7(), "rule__S__Group_7__0");
					put(grammarAccess.getSAccess().getGroup_7_2_0(), "rule__S__Group_7_2_0__0");
					put(grammarAccess.getSAccess().getGroup_8(), "rule__S__Group_8__0");
					put(grammarAccess.getFCAccess().getGroup(), "rule__FC__Group__0");
					put(grammarAccess.getFCAccess().getGroup_2(), "rule__FC__Group_2__0");
					put(grammarAccess.getFCAccess().getGroup_2_1(), "rule__FC__Group_2_1__0");
					put(grammarAccess.getBSAccess().getGroup_1(), "rule__BS__Group_1__0");
					put(grammarAccess.getFPAccess().getGroup(), "rule__FP__Group__0");
					put(grammarAccess.getPARFORPARAMSAccess().getGroup(), "rule__PARFORPARAMS__Group__0");
					put(grammarAccess.getPARAMSAccess().getGroup_0(), "rule__PARAMS__Group_0__0");
					put(grammarAccess.getPARAMSAccess().getGroup_1(), "rule__PARAMS__Group_1__0");
					put(grammarAccess.getPARAMSAccess().getGroup_2(), "rule__PARAMS__Group_2__0");
					put(grammarAccess.getPARAMSAccess().getGroup_3(), "rule__PARAMS__Group_3__0");
					put(grammarAccess.getPARAMSAccess().getGroup_4(), "rule__PARAMS__Group_4__0");
					put(grammarAccess.getPARAMSAccess().getGroup_5(), "rule__PARAMS__Group_5__0");
					put(grammarAccess.getPARAMSAccess().getGroup_6(), "rule__PARAMS__Group_6__0");
					put(grammarAccess.getPARAMSAccess().getGroup_7(), "rule__PARAMS__Group_7__0");
					put(grammarAccess.getDIAccess().getGroup_0(), "rule__DI__Group_0__0");
					put(grammarAccess.getDIAccess().getGroup_0_1(), "rule__DI__Group_0_1__0");
					put(grammarAccess.getISAccess().getGroup(), "rule__IS__Group__0");
					put(grammarAccess.getISAccess().getGroup_1(), "rule__IS__Group_1__0");
					put(grammarAccess.getPLAccess().getGroup(), "rule__PL__Group__0");
					put(grammarAccess.getPLAccess().getGroup_1(), "rule__PL__Group_1__0");
					put(grammarAccess.getEAccess().getGroup_0(), "rule__E__Group_0__0");
					put(grammarAccess.getEAccess().getGroup_1(), "rule__E__Group_1__0");
					put(grammarAccess.getEAccess().getGroup_1_1(), "rule__E__Group_1_1__0");
					put(grammarAccess.getTEAccess().getGroup_0(), "rule__TE__Group_0__0");
					put(grammarAccess.getSPKVAccess().getGroup(), "rule__SPKV__Group__0");
					put(grammarAccess.getPEAccess().getGroup(), "rule__PE__Group__0");
					put(grammarAccess.getPEAccess().getGroup_0(), "rule__PE__Group_0__0");
					put(grammarAccess.getTANAccess().getGroup(), "rule__TAN__Group__0");
					put(grammarAccess.getMTAccess().getGroup_0(), "rule__MT__Group_0__0");
					put(grammarAccess.getIDAccess().getGroup_2(), "rule__ID__Group_2__0");
					put(grammarAccess.getIDAccess().getGroup_2_1(), "rule__ID__Group_2_1__0");
					put(grammarAccess.getDAccess().getFAssignment_0(), "rule__D__FAssignment_0");
					put(grammarAccess.getDAccess().getSAssignment_1(), "rule__D__SAssignment_1");
					put(grammarAccess.getFAccess().getNameAssignment_0_0(), "rule__F__NameAssignment_0_0");
					put(grammarAccess.getFAccess().getIAssignment_0_4(), "rule__F__IAssignment_0_4");
					put(grammarAccess.getFAccess().getRAssignment_0_6_2(), "rule__F__RAssignment_0_6_2");
					put(grammarAccess.getFAccess().getSAssignment_0_8(), "rule__F__SAssignment_0_8");
					put(grammarAccess.getFAccess().getNameAssignment_1_0(), "rule__F__NameAssignment_1_0");
					put(grammarAccess.getFAccess().getIAssignment_1_4(), "rule__F__IAssignment_1_4");
					put(grammarAccess.getFAccess().getRAssignment_1_6_2(), "rule__F__RAssignment_1_6_2");
					put(grammarAccess.getFAccess().getSpkvAssignment_1_10_0(), "rule__F__SpkvAssignment_1_10_0");
					put(grammarAccess.getFAccess().getSpkvAssignment_1_10_1_1(), "rule__F__SpkvAssignment_1_10_1_1");
					put(grammarAccess.getSAccess().getSrcAssignment_0_2(), "rule__S__SrcAssignment_0_2");
					put(grammarAccess.getSAccess().getSrcidAssignment_0_5(), "rule__S__SrcidAssignment_0_5");
					put(grammarAccess.getSAccess().getCwdAssignment_1_2(), "rule__S__CwdAssignment_1_2");
					put(grammarAccess.getSAccess().getIfeAssignment_2_2(), "rule__S__IfeAssignment_2_2");
					put(grammarAccess.getSAccess().getIsAssignment_2_4(), "rule__S__IsAssignment_2_4");
					put(grammarAccess.getSAccess().getEsAssignment_2_5_1(), "rule__S__EsAssignment_2_5_1");
					put(grammarAccess.getSAccess().getFpAssignment_3_2(), "rule__S__FpAssignment_3_2");
					put(grammarAccess.getSAccess().getPAssignment_3_3(), "rule__S__PAssignment_3_3");
					put(grammarAccess.getSAccess().getSAssignment_3_5(), "rule__S__SAssignment_3_5");
					put(grammarAccess.getSAccess().getPfAssignment_4_2(), "rule__S__PfAssignment_4_2");
					put(grammarAccess.getSAccess().getPAssignment_4_3(), "rule__S__PAssignment_4_3");
					put(grammarAccess.getSAccess().getSAssignment_4_5(), "rule__S__SAssignment_4_5");
					put(grammarAccess.getSAccess().getWeAssignment_5_2(), "rule__S__WeAssignment_5_2");
					put(grammarAccess.getSAccess().getSAssignment_5_4(), "rule__S__SAssignment_5_4");
					put(grammarAccess.getSAccess().getDiAssignment_6_1(), "rule__S__DiAssignment_6_1");
					put(grammarAccess.getSAccess().getDiAssignment_6_2_1(), "rule__S__DiAssignment_6_2_1");
					put(grammarAccess.getSAccess().getFcAssignment_6_5(), "rule__S__FcAssignment_6_5");
					put(grammarAccess.getSAccess().getLhsdiAssignment_7_0(), "rule__S__LhsdiAssignment_7_0");
					put(grammarAccess.getSAccess().getDiAssignment_7_2_0_2(), "rule__S__DiAssignment_7_2_0_2");
					put(grammarAccess.getSAccess().getEAssignment_7_2_0_4(), "rule__S__EAssignment_7_2_0_4");
					put(grammarAccess.getSAccess().getEAssignment_7_2_1(), "rule__S__EAssignment_7_2_1");
					put(grammarAccess.getSAccess().getFcAssignment_8_0(), "rule__S__FcAssignment_8_0");
					put(grammarAccess.getFCAccess().getBifAssignment_0_0(), "rule__FC__BifAssignment_0_0");
					put(grammarAccess.getFCAccess().getIdAssignment_0_1(), "rule__FC__IdAssignment_0_1");
					put(grammarAccess.getFCAccess().getPeAssignment_2_0(), "rule__FC__PeAssignment_2_0");
					put(grammarAccess.getFCAccess().getPeAssignment_2_1_1(), "rule__FC__PeAssignment_2_1_1");
					put(grammarAccess.getBSAccess().getSingleSAssignment_0(), "rule__BS__SingleSAssignment_0");
					put(grammarAccess.getBSAccess().getSAssignment_1_1(), "rule__BS__SAssignment_1_1");
					put(grammarAccess.getFPAccess().getIdAssignment_0(), "rule__FP__IdAssignment_0");
					put(grammarAccess.getFPAccess().getIsAssignment_2(), "rule__FP__IsAssignment_2");
					put(grammarAccess.getPARFORPARAMSAccess().getParamsAssignment_1(), "rule__PARFORPARAMS__ParamsAssignment_1");
					put(grammarAccess.getDIAccess().getIdAssignment_0_0(), "rule__DI__IdAssignment_0_0");
					put(grammarAccess.getDIAccess().getBAssignment_0_1_1(), "rule__DI__BAssignment_0_1_1");
					put(grammarAccess.getDIAccess().getEAssignment_0_1_3(), "rule__DI__EAssignment_0_1_3");
					put(grammarAccess.getDIAccess().getClidAssignment_1(), "rule__DI__ClidAssignment_1");
					put(grammarAccess.getDIAccess().getClnAssignment_2(), "rule__DI__ClnAssignment_2");
					put(grammarAccess.getISAccess().getE1Assignment_0(), "rule__IS__E1Assignment_0");
					put(grammarAccess.getISAccess().getE2Assignment_1_1(), "rule__IS__E2Assignment_1_1");
					put(grammarAccess.getPLAccess().getTAssignment_0(), "rule__PL__TAssignment_0");
					put(grammarAccess.getPLAccess().getTAssignment_1_1(), "rule__PL__TAssignment_1_1");
					put(grammarAccess.getEAccess().getOpAssignment_0_0(), "rule__E__OpAssignment_0_0");
					put(grammarAccess.getEAccess().getT1Assignment_0_1(), "rule__E__T1Assignment_0_1");
					put(grammarAccess.getEAccess().getT1Assignment_1_0(), "rule__E__T1Assignment_1_0");
					put(grammarAccess.getEAccess().getOpAssignment_1_1_0(), "rule__E__OpAssignment_1_1_0");
					put(grammarAccess.getEAccess().getT2Assignment_1_1_1(), "rule__E__T2Assignment_1_1_1");
					put(grammarAccess.getTEAccess().getEAssignment_0_1(), "rule__TE__EAssignment_0_1");
					put(grammarAccess.getTEAccess().getIAssignment_1(), "rule__TE__IAssignment_1");
					put(grammarAccess.getTEAccess().getDAssignment_2(), "rule__TE__DAssignment_2");
					put(grammarAccess.getTEAccess().getSAssignment_3(), "rule__TE__SAssignment_3");
					put(grammarAccess.getTEAccess().getBAssignment_4(), "rule__TE__BAssignment_4");
					put(grammarAccess.getTEAccess().getBAssignment_5(), "rule__TE__BAssignment_5");
					put(grammarAccess.getTEAccess().getFAssignment_6(), "rule__TE__FAssignment_6");
					put(grammarAccess.getTEAccess().getDiAssignment_7(), "rule__TE__DiAssignment_7");
					put(grammarAccess.getSPKVAccess().getKAssignment_0(), "rule__SPKV__KAssignment_0");
					put(grammarAccess.getSPKVAccess().getVAssignment_2(), "rule__SPKV__VAssignment_2");
					put(grammarAccess.getPEAccess().getIdAssignment_0_0(), "rule__PE__IdAssignment_0_0");
					put(grammarAccess.getPEAccess().getEAssignment_1(), "rule__PE__EAssignment_1");
					put(grammarAccess.getTANAccess().getTAssignment_0(), "rule__TAN__TAssignment_0");
					put(grammarAccess.getTANAccess().getNameAssignment_1(), "rule__TAN__NameAssignment_1");
					put(grammarAccess.getIDAccess().getNameAssignment_0(), "rule__ID__NameAssignment_0");
					put(grammarAccess.getIDAccess().getNameAssignment_1(), "rule__ID__NameAssignment_1");
					put(grammarAccess.getIDAccess().getNameAssignment_2_0(), "rule__ID__NameAssignment_2_0");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalDmlParser typedParser = (InternalDmlParser) parser;
			typedParser.entryRuleD();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
