/*
 * generated by Xtext 2.9.0
 */
package sysml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDmlScopeProvider extends DelegatingScopeProvider {
}
