/**
 * generated by Xtext 2.9.0
 */
package sysml.validation;

import sysml.validation.AbstractDmlValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DmlValidator extends AbstractDmlValidator {
}
