/*
 * generated by Xtext 2.9.0
 */
package sysml.idea.completion;

import org.eclipse.xtext.idea.completion.AbstractCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractDmlCompletionContributor extends AbstractCompletionContributor {
	public AbstractDmlCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
