/*
 * generated by Xtext 2.9.0
 */
package sysml.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import sysml.idea.lang.DmlLanguage;

public class DmlExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return DmlLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
