/**
 * generated by Xtext 2.9.0
 */
package sysml.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class DmlFacetConfiguration /* implements AbstractFacetConfiguration, PersistentStateComponent<GeneratorConfigurationState>  */{
}
