/**
 * generated by Xtext 2.9.0
 */
package sysml;

import sysml.AbstractDmlRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DmlRuntimeModule extends AbstractDmlRuntimeModule {
}
