/**
 * generated by Xtext 2.9.0
 */
package sysml;

import sysml.DmlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DmlStandaloneSetup extends DmlStandaloneSetupGenerated {
  public static void doSetup() {
    DmlStandaloneSetup _dmlStandaloneSetup = new DmlStandaloneSetup();
    _dmlStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
